FROM node:16 AS build
ARG REACT_APP_APIURL 
ENV  REACT_APP_APIURL=${REACT_APP_APIURL}

WORKDIR /app
COPY  package*.json .
RUN   npm install
COPY   . .
RUN  npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]