version: '3.8'

services:
  frontend:
    container_name: react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"

  serverside:
    container_name: express-app
    build:
      context: ./serverside
    ports:
      - "4500:4500"
    command: ["node", "server"]

